<a href="https://colab.research.google.com/github/raphaellins/ai-playground/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sys

Python Multidimencional library, and FAST

In [ ]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3])

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [ ]:
#Get Dimension
a.ndim
b.ndim

2

In [ ]:
#Get Shape
a.shape
b.shape

(2, 3)

In [ ]:
#Get Tyoe
a.dtype
b.dtype

dtype('float64')

In [ ]:
a.itemsize
b.itemsize

8

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [ ]:
#Get specific element [row, column]

a[1, 5]

13

In [ ]:
#Get specif row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get specifc column
a[:, 2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy [ startindex:endindex:stepsize]

a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[1, 5] = 20
a[:,2] = 5
a[:, 2] = [1,2]

In [ ]:
b =np.array([[[1,2],[3,4]], [5,6],[7,8]])
b

array([[list([1, 2]), list([3, 4])],
       [5, 6],
       [7, 8]], dtype=object)

In [ ]:
b[:,1,:] = [[999,888]]

In [ ]:
np.zeros(5)

In [3]:
n = np.array([1,2,3])
n

array([1, 2, 3])

In [4]:
multidimensionalArray = np.array([[456, 123], [2003,982]])
multidimensionalArray

array([[ 456,  123],
       [2003,  982]])