<a href="https://colab.research.google.com/github/raphaellins/ai-playground/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sys

Python Multidimencional library, and FAST

In [2]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3])

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [5]:
#Get Dimension
a.ndim
b.ndim

2

In [6]:
#Get Shape
a.shape
b.shape

(2, 3)

In [7]:
#Get Tyoe
a.dtype
b.dtype

dtype('float64')

In [8]:
a.itemsize
b.itemsize

8

In [9]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a.shape

(2, 7)

In [10]:
#Get specific element [row, column]

a[1, 5]

13

In [11]:
#Get specif row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
#Get specifc column
a[:, 2]

array([ 3, 10])

In [13]:
#Getting a little more fancy [ startindex:endindex:stepsize]

a[0, 1:6:2]

array([2, 4, 6])